"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var svgo_1 = require("./svgo");
exports.svgo = svgo_1.svgo;
var svg2Definition_1 = require("./svg2Definition");
exports.svg2Definition = svg2Definition_1.svg2Definition;
var useTemplate_1 = require("./useTemplate");
exports.useTemplate = useTemplate_1.useTemplate;
var render_1 = require("./render");
exports.useRender = render_1.useRender;
