"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var clean_1 = require("./clean");
exports.clean = clean_1.clean;
var copy_1 = require("./copy");
exports.copy = copy_1.copy;
var generateEntry_1 = require("./generateEntry");
exports.generateEntry = generateEntry_1.generateEntry;
var generateIcons_1 = require("./generateIcons");
exports.generateIcons = generateIcons_1.generateIcons;
var generateInline_1 = require("./generateInline");
exports.generateInline = generateInline_1.generateInline;
